### ISSUE TITLE
[node-manager] minPerZone = 0 with maxPerZone > 0 paradox

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#1241]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.30

### Expected Behavior

There should be special validation for minPerZone = 0 to prevent setting maxPerZone > 0.
Or cluster autoscaler should be configured not to generate errors.

### Actual Behavior

It is possible to create NG with `minPerZone:  0` and `maxPerZone: 1`. If Nodes count is zero, the cluster-autoscaler generates an error:
```
E0331 17:34:28.349868       1 static_autoscaler.go:428] Failed to scale up: Could not compute total resources: No node info for: k-azure-sentry-cbe28926
```

After that we have `D8ClusterAutoscalerTooManyErrors` alert.

**Comment by konstantin-axenov** [comment]
@yalosev Isn't it fixed in 1.31 release with update cluster-autoscaler version?

**Comment by apolovov** [comment]
I've made the pr during friday meet but not sure is it a relevant solution, there could be NG without nodes but they must autoscale after deploying some Pod with appropriate nodeSelector.

**Comment by yalosev** [comment]
`Scale from zero` feature was [added](https://github.com/gardener/autoscaler/pull/102) in the [0.19](https://github.com/gardener/autoscaler/releases/tag/v0.19.0) cluster-autoscaler version. Probably, we need to make some changes from our side.
Also, would be nice to update to [v1.20](https://github.com/gardener/autoscaler/releases/tag/v1.20.0) version because it has some fixes for this feature
