### ISSUE TITLE
All Extended Monitoring alerts must have some label or annotation for easy filtering and post-processing 

### ISSUE THREAD

**Issue by kramarama** [deckhouse/deckhouse#1244]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have several projects on support with Deckhouse installed and extended monitoring is enabled for customer applications in production namespaces. Projects vary by size and scope of work; some projects are supported in full and all the alerts from the cluster go to the devops team to handle. Other projects are a bit trickier; our team only deals with a subset of applications running in the cluster, for instance, stateful stuff like databases and caches, or special applications in several namespaces, or only infrastructure services. Therefore there’s a need to separate the alerts from several groups of services running in the cluster and be able to differentiate alerts from extended monitoring from other alerts provided by Prometheus.

### Proposed Solution

 Instead of searching and listing all the trigger names that are available in the extended monitoring module I would just like to filter all the alerts by using labels like  tier=application and a NEW annotation or label, which might look like deckhouse=ext-monitoring. It would be much easier to redirect such alerts to post-processing by matching these labels to the proper team responsible for this service by using remap or a filter condition.

**Comment by EvgenySamoylov** [comment]
It doesn't look like adding the "extended-monitoring" label is a good solution for split alerts by different support teams because of the projects' diversity. All clients have their own scope of responsibility, but the extended monitoring has a fixed set of alerts so it's not convenient to use it that way. I suggest using the "tier" label to group alerts for "application" and "cluster" or just explicitly list the needed triggers on the alert manager's side.
