### ISSUE TITLE
[linter] force using same libraries

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#1490]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We tend to use different public libraries to solve identical tasks.
For example:
`040-control-plane-manager/hooks/audit_policy_test.go` imports `sigs.k8s.io/yaml`
but 
`810-deckhouse-web/hooks/get_deckhouse_tag_and_version.go` imports `gopkg.in/yaml.v3`

### Proposed Solution

We should lint some common libraries to force using the same implementation.
It will help to optimize the d8 binary size, memory, building time, etc.

**Comment by nabokihms** [comment]
@apolovov, there is a problem that they behave differently.

1. We use the `sigs.k8s.io/yaml` package to mimic Kubernetes. It is based on the yaml.v2 package uses JSON tags for marshaling/unmarshalling and empty interfaces for map keys. And there is one more thing - yaml.v2 ok with the following snippet
```yaml
kind: Service
kind: Deployment
```
2. The `gopkg.in/yaml.v3` we use when we want to validate something, e.g., generated manifests, because it throws an error for the following snippet
```yaml
kind: Service
kind: Deployment
```
You can read more about yaml.v2/v3 difference here https://ubuntu.com/blog/api-v3-of-the-yaml-package-for-go-is-available

**Comment by nabokihms** [comment]
BTW, if we decide to go with this feature, there is a linter called depguard for exactly this case. 

Example:
https://github.com/dexidp/dex/blob/fd15dd2248900a16849af9513d9a70c0a0e5103f/.golangci.yml#L5-L11
