### ISSUE TITLE
[log-shipper] Add liveness probe for kube-rbac-proxy 

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#1596]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.32

### Expected Behavior

Liveness probe helps log-shipper to recover after failure.

### Actual Behavior

Liveness probe for vector container is a request to kube-rbac-proxy. When kube-rbac-proxy hangs, vector container is constantly restarted, but it doesn't help.
```
  Warning  Unhealthy  13m (x3918 over 29h)    kubelet  Readiness probe failed: Get "https://10.244.254.201:9254/api/health": dial tcp 10.244.254.201:9254: connect: connection refused
  Warning  BackOff    8m14s (x4420 over 29h)  kubelet  Back-off restarting failed container
  Warning  Unhealthy  3m19s (x3688 over 29h)  kubelet  Liveness probe failed: Get "https://10.244.254.201:9254/api/health": dial tcp 10.244.254.201:9254: connect: connection refused
```

### Steps To Reproduce

It is a rare situation that happens when a node encounters system oom.

**Comment by nabokihms** [comment]
My idea is to duplicate the same probes for the kube-rbac-proxy container, but with higher thresholds for failed attempts. If the problem is with application, it will be restarted first (kube-rbac-proxy will remain still). If the problem is with the kube-rbac-proxy container, it will be restarted if application restart did not fix the problem.
