### ISSUE TITLE
[linstor][bashible]  install-kernel-headers.sh not work in debian 11

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#4801]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45.10

### Expected Behavior

linux-headers install

### Actual Behavior

linux-headers not install

### Additional Information

https://t.me/deckhouse_ru/20913

**Comment by wowsel** [comment]
Hello!
`May 29 13:02:55 co-k8s2m3 bashible.sh[327192]: ===
May 29 13:02:55 co-k8s2m3 bashible.sh[327192]: === Step: /var/lib/bashible/bundle_steps/200_install-kernel-headers.sh
May 29 13:02:55 co-k8s2m3 bashible.sh[327192]: ===
May 29 13:02:55 co-k8s2m3 bashible.sh[331518]: error: error parsing STDIN: error converting YAML to JSON: yaml: line 9: did not find
expected key
May 29 13:02:55 co-k8s2m3 bashible.sh[331526]: bb-apt [INFO] Removing packages 'linux-headers-5.10.0-23-common'
May 29 13:02:55 co-k8s2m3 bashible.sh[331578]: Reading package lists...
May 29 13:02:55 co-k8s2m3 bashible.sh[331578]: Building dependency tree...
May 29 13:02:55 co-k8s2m3 bashible.sh[331578]: Reading state information...
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: Some packages could not be installed. This may mean that you have
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: requested an impossible situation or if you are using the unstable
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: distribution that some required packages have not yet been created
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: or been moved out of Incoming.
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: The following information may help to resolve the situation:
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: The following packages have unmet dependencies:
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]:  linux-headers-5.10.0-23-amd64 : Depends: linux-headers-5.10.0-23-common (= 5.10.179-1
) but it is not going to be installed
May 29 13:02:56 co-k8s2m3 bashible.sh[331526]: E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held pac
kages.
May 29 13:02:56 co-k8s2m3 bashible.sh[327192]: Failed to execute step /var/lib/bashible/bundle_steps/200_install-kernel-headers.sh ..
. retry in 10 seconds.`

If I do that 
`May 29 13:02:55 co-k8s2m3 bashible.sh[327192]: ===
May 29 13:02:55 co-k8s2m3 bashible.sh[327192]: === Step: /var/lib/bashible/bundle_steps/200_install-kernel-headers.sh
May 29 13:02:55 co-k8s2m3 bashible.sh[327192]: ===
May 29 13:02:55 co-k8s2m3 bashible.sh[331518]: error: error parsing STDIN: error converting YAML to JSON: yaml: line 9: did not find
expected key
May 29 13:02:55 co-k8s2m3 bashible.sh[331526]: bb-apt [INFO] Removing packages 'linux-headers-5.10.0-23-common'
May 29 13:02:55 co-k8s2m3 bashible.sh[331578]: Reading package lists...
May 29 13:02:55 co-k8s2m3 bashible.sh[331578]: Building dependency tree...
May 29 13:02:55 co-k8s2m3 bashible.sh[331578]: Reading state information...
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: Some packages could not be installed. This may mean that you have
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: requested an impossible situation or if you are using the unstable
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: distribution that some required packages have not yet been created
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: or been moved out of Incoming.
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: The following information may help to resolve the situation:
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]: The following packages have unmet dependencies:
May 29 13:02:56 co-k8s2m3 bashible.sh[331578]:  linux-headers-5.10.0-23-amd64 : Depends: linux-headers-5.10.0-23-common (= 5.10.179-1
) but it is not going to be installed
May 29 13:02:56 co-k8s2m3 bashible.sh[331526]: E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held pac
kages.
May 29 13:02:56 co-k8s2m3 bashible.sh[327192]: Failed to execute step /var/lib/bashible/bundle_steps/200_install-kernel-headers.sh ..
. retry in 10 seconds.`
it will work, but a day later the old problem again.

**Comment by wowsel** [comment]
The problem is that Debian uses a metapackage named linux-headers-5.10.0-23-common and the current script is trying to remove the common package, which cannot be done. it will be deleted by itself when amd64 is removed, but it is not necessary to remove and install it separately. you don't need to touch it at all.
