### ISSUE TITLE
[docs] Use relative links by default

### ISSUE THREAD

**Issue by kvaps** [deckhouse/deckhouse#484]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

As mentioned in https://github.com/deckhouse/deckhouse/pull/435#discussion_r774438364 the  current documentation includes many links to https://deckhouse.io.

We build documentation for every client and have custom hook to correct the links.
It would be nice to have the links correct from beginning.

### Proposed Solution

- Replace all links to relative ones
- Get rid of this task:
  https://github.com/deckhouse/deckhouse/blob/e88ca3236c37a4a88e5a7fadc23ebac372f0089f/modules/810-deckhouse-web/images/web/werf.inc.yaml#L106-L112

**Comment by z9r5** [comment]
We have to use absolute links in resources (in CRD OpenAPI schemas). It does not matter in the case of the public site, but inside a cluster, it is better to use only relative links. So we convert absolute links to a relative when building the deckhouse-web module image.

Don't see a lot of absolute links in the documentation section to replace.
But it is better to use {{ site.url }} instead of deckhouse.io. And, maybe, we need a linter.
