### ISSUE TITLE
[ci][testing] EKS resource naming

### ISSUE THREAD

**Issue by z9r5** [deckhouse/deckhouse#5365]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Resources created by EKS test have to contain github action job number, instance number, K8s version.

### Proposed Solution

Use the format already used in other tests.

**Comment by konstantin-axenov** [comment]
@duckhawk Can you describe all TODOs for EKS testing in this Issue, please?

**Comment by duckhawk** [comment]
Actual TODOs is:
- Incorrect resources naming in tests (random hash instead of test-related names)
- Incorrect layout WithoutNAT (in fact, there is no layouts for EKS)
- When test fails, there is incorrect ssh connection string in comment (EKS cluster is reachable via generated kubectl config file only, not ssh)
