### ISSUE TITLE
[prometheus] Add dashboard etcd response time data

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#614]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We should observe the state of slowed etcd which is not directly clear from current etcd dashboard

### Proposed Solution

Create dashboards with at list recommended requests from the page https://etcd.io/docs/v2.3/metrics/#http-requests

**Comment by gmaiorov** [comment]
`etcd_http_` metrics were removed from etcd since 3.0 during transition from HTTP API to GRPC.
I'm planning to add `grpc_server_handling_seconds_bucket` & `etcd_network_peer_round_trip_time_seconds_bucket` .99 quantile graphs as a replacement.
`etcd_network_peer_round_trip_time_seconds_bucket` replaces `etcd_http_successful_duration_seconds_bucket` to some extent & allows to detect GRPD request time slowdown.
