### ISSUE TITLE
[ingress-nginx] Add enable-ssl-passthrough as a parameter

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#7445]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

This feature allows nginx-controller to pass non-HTTP TLS+SNI traffic to an application that doesn't use HTTP
https://kubernetes.github.io/ingress-nginx/user-guide/tls/#ssl-passthrough

### Proposed Solution

Add a parameter to `IngressNginxController` resource that adds `--enable-ssl-passthrough` arg to ingress-controller

It was tested and working when adding an arg manually to a controller daemonset.apps.kruise.io

**Comment by konstantin-axenov** [comment]
There are several things that have to be considered:

- Unlike HTTP backends, traffic to Passthrough backends is sent to the clusterIP of the backing Service instead of individual Endpoints.
- This feature is implemented by intercepting all traffic on the configured HTTPS port (default: 443) and handing it over to a local TCP proxy. This bypasses NGINX completely and introduces a non-negligible performance penalty.
- If there is no hostname matching the requested host name, the request is handed over to NGINX on the configured passthrough proxy port (default: 442), which proxies the request to the default backend.
- [Unable to maintain client IP with SSL Passthrough in Ingress NGINX Controller](https://github.com/kubernetes/ingress-nginx/issues/10706)
- [When ssl-passthrough is enabled at the same time as proxy-protocol, proxy-proto doesn't work.](https://github.com/kubernetes/ingress-nginx/issues/10181)
- [Host wildcard with SSL passthroug](https://github.com/kubernetes/ingress-nginx/issues/9473)
- HostWithFailover inlet doesn't work

**Comment by konstantin-axenov** [comment]
We think about adding new ingress controller that will be able to do ssl passthrough. And this should resolve the issue.

**Comment by konstantin-axenov** [comment]
We reconsidered. Seems that we need to add two new inlets HostPortWithSSLPaththrough and LoadBalancerWithSSLPaththrough.
