### ISSUE TITLE
[dhctl] There isn't error message for failed detect_bundle script

### ISSUE THREAD

**Issue by tarabrind** [deckhouse/deckhouse#8356]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.10

### Expected Behavior

dhtcl bootstrap have to show the error messages from detect_bundle.sh.

### Actual Behavior

Trying to install d8 to Debian 12 powered VM. It isn't supported by d8 in this release, but the messages from dhctl bootstrap aren't informative:
```shell
[deckhouse] root@30781928e0f5 / # dhctl bootstrap ...
...
┌ ⛵ ~ Bootstrap: Detect Bashible Bundle
└ ⛵ ~ Bootstrap: Detect Bashible Bundle (3.83 seconds) FAILED

timeout while "Get bundle": last error: detect_bundle.sh: execute on remote: exit status 1
```

**Comment by nabokihms** [comment]
It seems like we printing stderr in case of exec error
https://github.com/deckhouse/deckhouse/blob/ee25c56eb896e08bb3ebeaf36c3d23eef9d102c4/dhctl/pkg/operations/bootstrap/steps.go#L372-L378

Probably the error is not because of the script, but something else.
https://cs.opensource.google/go/go/+/refs/tags/go1.22.3:src/os/exec/exec.go;l=596-597

Another option is to print more output during detect bundle scrept, e.g. `Detection started`, `Detection finished`.
