### ISSUE TITLE
cert-manager does not work with Ingress Nginx's proxy-protocol mode

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#841]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.30.10

### Expected Behavior

A certificate is successfully validated by let's encrypt.

### Actual Behavior

Certificates are not validated.

### Additional Information

cert-manager performs self-check before submitting a request for external validation to Let's Encrypt servers. Since kube-proxy intercepts traffic destined to External IP of a LoadBalancer Service and redirects it internally. Since OpenStack's (or other) LB does not add PROXY protocol headers, nginx rejects such a request.

1. There is [a workaround](https://github.com/cert-manager/cert-manager/issues/466#issuecomment-715588848) with HAproxy and CoreDNS rewrite rules to redirect internal traffic.
2. There is [an extension](https://github.com/kubernetes/kubernetes/pull/97681/) to the Service object in the works which will solve this issue.

**Comment by nabokihms** [comment]
Related Kubernetes issue, which contains many fascinating examples (consist of pure pain) https://github.com/kubernetes/kubernetes/issues/66607

I managed to find [this issue](https://github.com/kubernetes/cloud-provider-openstack/pull/1449) about adding a flag to the OpenStack CCM to make it act like the AWS CCM - set hostnames instead of IP addresses. The doc about how to preserve client ips by enabling proxy protocol [is here](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md#use-proxy-protocol-to-preserve-client-ip). 

The release with the fix for our problem is the [v1.21.0](https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.21.0).
