### ISSUE TITLE
Dhctl bootstrap freezes if has bastion

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#844]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.30.0

### Expected Behavior

Dhctl should connects to master and bootstraps it. 

### Actual Behavior

Dhctl bootstrap freezes with message `Connect to master host` without any errors.

If pass `-v` argument to `--ssh-extra-args` ssh says `SSH client: Connection timed out during banner exchange`

If add all hosts to `~/.ssh/known_hosts` bootstrap will start normally.

### Additional Information

Probably we do not pass [this argument](https://github.com/deckhouse/deckhouse/blob/e8ac69d3f4a7da08cf57f2244846fc1b2eb7af0d/dhctl/pkg/system/ssh/cmd/ssh.go#L74) to proxy command

**Comment by nabokihms** [comment]
The actual problem is the `ProxyComand` option of the ssh-config.

For dhctl ssh-host and bastion-ssh-host, the determined set of options is used, like automatically accepting new hosts or using the different the known_hosts file.
https://github.com/deckhouse/deckhouse/blob/315f60c681b1dbe955dab255154bde36542b6331/dhctl/pkg/system/ssh/cmd/ssh.go#L69-L78

However, ProxyCommand does not respect our settings and uses default values. As of today, the only idea is to copy ssh config to a tmp file and then add our ssh args to all ProxyCommand.
